In [ ]:
"""
LIST ,Array
1.List is an ordered sequence of data;ArraySimilar to a list,[ 1, 2, 3, 4, ‘b’, [ 1, 2, 3 ] ]
is a list containing integers, a string, and another list.
Python List:Takes a huge amount of time and memory for numerical computations of large data
Can contain data of different data types

2.NumPy Array:Very cheap in terms of time and memory for numerical computations of large data
Can contain data of same data type only
an array is also a data structure 
which can hold more than one value at a time but ordered elements of the same data type eg toy car of
different color,lineup them on shelf to keep organized;shelf like array and each toy car like an 
element in the array,you can identify each element in an array by its position like car on shelf
these would be called the first element, second element, and third element, respectively.

[1, 2, 3] is an array of integers.[ ‘a’, ‘b’ ] is an array of strings.
[[ 1 , 2 , 3 , 4],[ 5, 6, 7, 8 ]] is a 2 dimensional array.
Why Arrays?A combination of Arrays, together with Python could save you a lot of time.reduce the 
overall size of your code.

3.Dimensions
A box has three dimensions - width, length and depth (or height). Similarly,
in data science we will be working with “N” dimensions in a data structure 
(list, arrays, vectors etc). “N” could be any number.

Vectors & Matrix
4.A vector, in programming, is a type of array that is one-dimensional.For example, [1, 2, 3, 4, 5]
eg one row of toy cars in box car1,car2,car3;other words,the array has only one dimension or direction.
In contrast, if you had a box with multiple rows of toy cars
two-dimensional array,because it has two dimensions,or directions(up and down, as well as left and right).

5.Matrix
Matrix is an arrangement of numbers into rows and columns.egbig square bracket[2 5 6
The matrix A has two rows and three columns. now think box as matrix          7 8 9 ]
and each toy car has an element in the matrix
A matrix is like a table of numbers that are organized into rows and columns.
Each toy car has a specific position in the matrix, based on its row and column.

6.Shape of Matrix
Since matrix A has two rows and three columns,we write its shape as 2*3 , pronounced as ‘two by three’.

7.Dimension of Matrix
The shape of the matrix also tells you its dimensions. The dimension of matrix A is 2
as its shape is 2 * 3.
you could use a vector to keep track of the scores in a game, 
or you could use a matrix to represent the positions of objects on a screen.(eg player 5 position)

8.Numpy 
NumPy stands for Numerical Python.It is an open-source Python library
Makes the numerical computations easier and faster ,Consumes less memory

9.What is an Array in NumPy?
Like list in Python an array is a data structure in NumPy.An Array in NumPy can hold collection of 
ordered elements,of same type.
an array being referred to as ‘ndarray’,which is shorthand for ‘N - dimensional array’.
An N - dimensional array is an array with n number of dimensions
1D Array: 7 2 9 10 ;==axis 0==; shape (4,) like 1 row 4 column = 4*1 = 4shape
2D Array 1 2 3  axis 0         shape (2,3)
         4 5 6
         ==axis 1==
3D Array  1 2 3                  1 2 (other side)
          4 5 6  axis 0          3 4
          7 8 9                  5 6
          1 2 3                  7 8
          axis 1                 axis 2
                  shape(4,3,2)

10.Attributes of an Array: Shape, Size and Data Type of an Array
The number of dimensions and items in an array is defined by its shape.
The dimensions are also called as axes.Suppose, if you have a 2D array that looks like this:
[[1,2,3],[4,5,6]]
In this case your array has two axes. First axis has length of two(2 rows first axis)
and the second axis has length of 3(3 columns second axis)

11
an electronic document in which data is arranged in the rows and columns 
of a grid and can be manipulated and used in calculations.like microsoft sheet,google sheet,
A CSV is a comma-separated values file, which allows data to be saved in a tabular format.

12.Data structures: can be classified into two groups, namely homogeneous and heterogeneous.

Homogeneous Data Structures: This type can only store a single type of data inside 
them(integer, character, etc.), Homogeneous means the same type.
Arrays are homogeneous, since you declare the single type as part of the definition.

Heterogeneous data Structures: This type can store more than one type of data at the same time
Class data tends to be heterogeneous as you have integers, strings, other classes, etc

13.
PAndas vs NumPy
Pandas is primarily used for data analysis. It supports working with tabular data like CSV,
Excel sheets, etc. 
NumPy, by default, supports data in the form of matrices and arrays since it
is focused on numerical computations.

Pandas is most commonly used for data wrangling and data manipulation purposes,
and NumPy objects are primarily used to create arrays or matrices that 
can be applied to DL or ML models. Whereas Pandas is used for creating heterogenous,
two-dimensional data objects, NumPy makes N-dimensional homogeneous objects.

Pandas is a popular open-source data manipulation and analysis library for Python. 
It provides easy-to-use data structures like DataFrame and Series, 
which are designed to make working with structured data fast, easy, and expressive.
Pandas are widely used in data science, machine learning, and data analysis for tasks
such as data cleaning, transformation, and exploration.

#What is the Pandas series?
A Pandas Series is a one-dimensional array-like object that can hold data 
of any type (integer, float, string, etc.). It is labelled, meaning each element
has a unique identifier called an index. You can think of a Series as a 
#column in a spreadsheet or a single column of a database table. Series are a fundamental
data structure in Pandas and are commonly used for data manipulation and analysis tasks.
They can be created from lists, arrays, dictionaries, and existing Series objects. 
Series are also a building block for the more complex Pandas DataFrame, 
which is a two-dimensional table-like structure consisting of multiple Series objects.

#What is Pandas Dataframe?
A Pandas DataFrame is a two-dimensional, tabular data structure with rows and columns. 
It is similar to a spreadsheet or a table in a relational database. 
The DataFrame has three main components: the data, which is stored in rows and columns; 
the rows, which are labeled by an index; and the columns, which are labeled and 
contain the actual data.

#np.nan
In Python, NumPy NAN stands for not a number and is defined as a substitute for declaring value
which are numerical values that are missing values in an array as NumPy is used to deal with 
arrays in Python and this can be initialized using numpy

#What is indices in NumPy?
#You can access an array element by referring to its index number. 
#label each value like N ,Y ,or by anynumber
14.
#Mean Mode Median
#Measures of central tendency help you find the middle, or the average, of a data set. 
#The 3 most common measures of central tendency are the mean, median and mode. 
#The mode is the most frequent value. The median is the middle number in an ordered data set.

#The mean can be used to get an overall idea, or picture, of the data set.
#Mean is best used for a data set with numbers that are close together. 
#The median can be used to get an idea of what values fall above the midpoint 
#and what values fall below the midpoint.
#The range is the difference between the biggest and the smallest numbe
#3, 3, 6, 13, 100
#The median is 6.    The mode is 3.    125 ÷ 5 = 25 The mean is 25  range=100-3=97

#Sir:Mean Median Mode is a study of data ka centre point kia hai
#hur jaga mean fill nhe hota,,chaha wo number ho
#data mein agar outlayer hein tu hum average nhe krta  outlier means 

#An outlier is a single data point that goes far outside the average(below or above the main pattern)
#value of a group of statistics.
#When a value is called an outlier it usually means that that value deviates from all other values
#in a data set. For example, in a group of 5 students the test grades were 9, 8, 9, 7, and 2. 
#The last value seems to be an outlier
#because it falls below the main pattern of the other grades.

# tu es surat mein beach ke  value :10 value,4 alag 4 alag .beach ke 2 ka average

#mode: jub  hamara pass (ordinal(tarteeb wala number),(non ordinal like ac number,telephone number
#)nominal)
#the most repeated item in the list.
#mode non numeric mein laga ga

#Standard deviation .std()
#Standard deviation describes how dispersed a set of data is relative to its means
#and is caluclated as the square root of the variance.
#calculated value that describes whether the data points are in close proximity 
#or whether they are spread out.

#variance .var()
#A measurment of how far each number in the data set is from the mean(average) and thus from
#every other number in the set

15.
#EDA:Exploratary Data Analysis
phala data analyize called EDA
akk akk column ko explore krna parta 
explore krna ka bayd 

16.Data Cleansing
Data Cleansing
analysis krna sai phala clean kara ga
es sai daikhan ga ka humara data ketna kharab hai jis ko hum na sahi krna hai
agar data proper nhe hu ga tu un pr jo assumpition ya decision making ho ge wo bhe sahi nhe hu ga
bayz dafa data kharab nhe hota,bayz dafa data us tarha nhe hota,jis tarha humyn chahya hota hai
tu humyn data clean kr ka transform krna parta hai

17. csv
#csv : for to store data,each value can be separated by delimiter like comma etc,,means ak value 
#khatam ho gaee,ya hum na simple notepad pr values lekhe/data lekha

18.#Avg value:mera jo data set hai us ka centre point kia hai,wo ya avg value hai
#eg age avg =25 ,nt necssary ka wo sari ages 25 hu ge,but wo sri ages 25 ka kareeb kareeb hu ge
#agar mein kahu mera data ka undar variance ketna hai,variance acutally study hote hai 
#dispersion of data
#Dispersion is the state of getting dispersed or spread. Statistical dispersion means
#the extent to which numerical data is likely to vary about an average value.
#In other words, dispersion helps to understand the distribution of the data.
#eg mein avg age jo centre us pr khara ho k dekho ga ka dosra larkoon ke age mein ketna variance
#hai centre point sai
#eg avg age 25,if someone age 29 .tu + 5 ka dispersion a raha,20 tu -5 la dispersion
#means Mean sai ketna deviate/inharaf/against kr raha hai
#Mean , Median , Mode are central tendency conversion of data ka sara data conversion kes point pr
#ho ga
#Mean Median Mode is the study of centre of data hai
#Mean fill hota number wala column mein,lakin hur jaga mean fill nhe hota ,chaha number wala column h
#hee kuu na ho
#eg company mein 50 employess salary max 1 lac but 2 employees 20 lac.tu avrage 280,000
#its wrong
#tu aise surat mein hum average nhe leta ,agar outlier hota hai tu
#outlier:jo region sai bohat dur,matlab ziada value sai dur
#*centre sai dur,average sai dur hota..it means en mein variance bohat ziada hai
#Median :phr hum median value nekalta hein,phr hum phala en ko sort krta hein eg 10 tu beach ke 2,
#11 hote tu 5 ,5 chor kar ,central ka one;
#its nw a data centre point ,ju humyn Mean sai nhe Median sai mel raha hai

#Mode: ka estemal tub kara ga ,jub hamara pass categorical data ho ga,non numeric data ho ga
#2 tarha ka data hota hai
#categorical :nos na hu,like male ,female etc
#numerical :further into 
#ordinal (nos jin ko tarteeb mein rakha ja saka) or 
#Nominal kuch data aisa hota jo numerical hona ka bawjood bhe ordinal nhe hota 

#Mode:The most repeated item in ths list

19. Lambda Function

#ya annoynumous function hota ,es ka name koe nhe hota
# **or ya ose cell mein istemal ho ga,wahan pr he khatam or dosra koe us ko call nhe kr sakta
#hum chahta alag function na banana para ,balka cell he mein nemut jaya

20. Discrete and Continuous data
#What is difference between discrete and continuous data?
#Discrete data is data that can be counted, but it can not be divided.
#The number of people in a room is an example of discrete data.
#Discrete value can not be 3.5 ,cant nt in decimal(but n necesaary),it always whole numbers

#Continuous data is data that can be measured, and it can be divided. 
#The height of a person is an example of continuous data.
#Conitunous value can be in decimal(not necessary eg age 7 ,weight exact 50kg)

#Note:not necessary both above should be in decimal or non decimal.we must see type of variable,
#feature kia hai, kis ko discuss kr raha hein,ya wo feature continuous feature hai ya discreate 
#feature hai

#Is age continuous or discrete?
#Age is considered to be continuous data. The number of years old a person is can be counted,
#but that be divided into the number of months, days, hours, etc.


21. BINNING
#Binning is a way to group a number of more or less continuous values into a smaller number of "bins".

#eg age wise group banao,hur banda individual ho ga,bc age kese ke same nhe ho ge.100 log hu ga tu
# 100 groups,
#tu hum group bana leta hein like 20 sai 30 sal wala ak group mein

#Just for Info:Noise can be handled using binning. In this technique, sorted data is placed 
#into bins or buckets.Bins can be created by equal-width (distance) or equal-depth (frequency) partitioning.
#On these bins, smoothing can be applied.


22.  Combination AND Permutation

In a combination, the elements of the subset can be listed in any order. 
#Selection of menu, food, clothes, subjects, the team are examples of combinations.

#In a permutation, the elements of the subset are listed in a specific order.
#Arranging people, digits, numbers, alphabets, letters, and colours are examples of permutations.

#*ketne tarha sai wo data arrange ho sakta hai,how many possible ways to arrange his data

# n!=n(n-1) * 
#nCr = n!/(n-r)!r!
#nPr = n!/(n-r)!
#eg 10people ,prizes 3,How many can the prize be distributed 10P3=10!/10!-3!

23.    Quantitative Data  &  Qualitative Data
#jub bhe hum kese data ko machine sai pass karwata hein,machine 0 ya 1 samjhte hai
# interger value tu binary 0 and 1 mein convert ho jaya ge
#string ka kia kara ga,akk jawab tu ya ka hur alphabet ka against akk ST value hote hai,jo number bun 
# jaya ga,jis ko binary mein convert kr dein ga
#es sai pata chala ka data ka classification hote hai,phale class numeric n non numeric
#phr kuch data qualitative and quatitive bhe hota hai


#Quantitative data is numbers-based, countable, or measurable. Qualitative data is 
#interpretation-based, descriptive, and relating to language. 
#Quantitative data tells us how many, how much, or how often in calculations. 
#consist of numerical survey responses, test scores, and data related to website traffic
#eg Age

#Qualitative data can help us to understand why, how, or what happened behind certain behaviors.
#allow for open-ended answers, transcripts from interviews, and notes taken from observations
#eg Gender,color

#QUalitative data further divide into two:
# Ordinal and Nominal

#Examples of nominal data include the country, gender, race, hair color, etc. of a group of people,
#Nominal Purely name
#while that of ordinal data includes having a position in class as “First” or “Second”. 
#Note that the nominal data examples are nouns, with no order to them while 
#ordinal data examples come with a level of order.
#Ordinal can be in order like food is ,Excellent,good,delicious,rich.en sb ko order mein lekha ja sakta
#hai

*** Nominal Purely name
#hum dummy value es lia get krta hein ka hamara nominal data ,understand tu machine language convert
# hu ,es tarha ka us ke nominality bhe bakee raha















"""

In [ ]:
0.#python list
list=[2,4,6,8]

1.#import numpy library
import numpy as np

2.# Converting the python_list to a numpy array
numpyarray=np.array(list)
numpyarray

3.# Create two python List say 'List_x' and 'List_your'
X_list = list(range(100000))
Y_list = list(range(100000))

def add():
    Z=[]

    for i in range(len(X_list)):
        Z.append(X_list[i]+Y_list[i])
           return Z
print(add())
        
4.# using numpy arrays (X, Y)
def numpy_version():
# In numpy we can directly perform ,sum element-wise as
X=np.array(X_list)
Y=np.array(Y_list)
    Z = X + Y 
    return Z
print(numpy_version())

5.# Import Timer class from timeit Library
#Notice the time taken by both the functions to perform the same task.
from timeit import Timer
timer_obj1 = Timer("Pyth()", 
                   "from __main__ import Pyth")
timer_obj2 = Timer("numP()", 
                   "from __main__ import numP")

print("Pyth version:",timer_obj1.timeit(1000))
print("Numpy version:",timer_obj2.timeit(1000))

#Shape, Size and Data Type of an Array
6.#Size of an Array
#NumPy array has an attribute called size that tells you the total number of elementsin the array
arr.size

7.#Data Types of Array
#The data type of array ‘arr’ is ‘int’ (integer). Here, ‘32’ is related to memory allocation.
arr.dtype

8.#Shape of an Array
#An array has an attribute called shape that tells you the number of items along each axis.
#If we have an array with two axes, the shape attribute will tell you the total number of rows 
#and columns in that array.
#The shape attribute of NumPy returns a tuple of integers that represents the number of items 
#along each axis
arr.shape

9.#Dimension of an Array/.ndim no of dimension
#An array has an attribute called dimension that tells you the number of axes in the array.
#You can check the number of dimensions of a NumPy array using the ‘.ndim’ attribute.
#The array ‘arr’ is 2 dimensional (i.e., the array has two axes).
arr.ndim

10.#the type of NumPy array
#Everything in Python is an object.In python type()
#the object is a NumPy ndarray. If you want to know the type of data present 
#in that array, you will use the attribute ‘.dtype’;#The numpy.ndarray is of type int32

11.#Creating Basic NumPy Arrays #array( )
#You can use the array() function to create a numpy array.
#You can see here the first row in arr is nothing but the first inner list [1, 2, 5, 7] and similarly the other rows are other inner lists index wise.
arr1=np.array([[1,2,5,7],[5,2,7,6],[6,2,0,8]])
arr1

12.#arange( )
#Use arange() function to create collection of continuous integers.
#you pass 5 in bracket, it will generate first 5 integers numbers from 0 to 4 (i.e. first 5 integers) 
#[ 0, 1, 2, 3, 4 ]
np.arange(5)

13.#Zeros( )
#The zeros() function creates an n-dimensional array of zeros. If no shape is specified, 
#then it will create a one-dimensional array:
arr=np.zeros(5)
arr

14.#ones( )
arr=np.ones(5)
arr
one1=np.ones([5,5])*10
one1

15.#linspace( )
#linspace() generates values which are equally spaced from each other.
#arr=np.linspace(start=5,stop=6,num=7)
arr=np.linspace(5,6,4)
arr
#If you don’t pass ‘num’ argument, it will generate 50 equally spaced values.

16.#Add, Remove and Sort
#Adding an Element
arr=np.array([2,5,7,3,4,6])
#Create a NumPy array:
arr
#You can use append method to add an element in a NumPy array:
np.append(arr,15)
#You can also add an element to a Python list using np.append() method.
#But the returned object is a NumPy array.
l=[1,2,3,4]
larr=np.append(l,15)
type(larr)

#You can also add a list of elements
#np.append(arr,[5,6,7])
np.append(arr,[larr])
#Python list supports append() method directly on the Python list ,but numPy doesnt support 
#directly ,use np

17.#Removing an Element
#arr=np.array([2,5,7,3,4,6])
np.delete(arr,2)
#7 deleted on index 2

18.#Sorting an Array
arr=np.array([5,2,7,8,4,6])
np.sort(arr)

19.#Reshaping an Array ;np.reshape()
#Using np.reshape() will change the shape of your array.
#Also, there won’t be any changes in the original data other than the shape.
#Caution: Whenever you use reshape() method, you need to make sure that the array you want 
#to produce after reshaping needs to have the same number of elements as the original array.
#Suppose you have an array with 24 elements. If you want to reshape this array,
#you need to make sure that your new array also has a total of 24 elements. 
#You can reshape this array into (8, 3), (6, 4), (12, 2), and so on, 
#as all these will also have total of 24 elements (8  3 = 24, 6  4 = 24, 12  2 = 24).
arr=np.arange(24)
#Create an array with 24 elements in it.
arr
#np.reshape(arr,(8,3))
np.reshape(arr,(6,4))
np.reshape(arr,(12,2))
#OR
#arr.reshape(6,4)
#using reshape method directly on array ie arr
#but using directly on python list will throw an error

#Reshaping a Python List
#Using np.reshape() you can change the shape of a Python list but the returned object 
#is of type numpy.ndarray, i.e., it becomes a NumPy array.

20.#Positive Indexing (python)
#You want to get the 3rd element from the array. 
#Use square brackets ([ ]) and pass the index number (2 in this case) in that square brackets
#as you used to do for Python lists.
arr=np.array([10,20,30,40])
arr[3]
#Positive Single Indexing in Python Nested List
pyt=[[10,20,30,40],[1,2,3,4]]
pyt[1][2]
#will get u the item present at 1 i.e here the second sub list
#then get the element present at index 2 in sub list

#Positive Single Indexing in a NumPy Array
#The array here is of dimension 2. You can compare Python nested list and a NumPy 2D array.
arr=np.array([[10,20,30,40],[1,2,3,4]])
arr[0]
#In NumPy 2D array, when you pass a single index in the square bracket,
#it will give you the entire row present at that index.
#You can pass comma-separated values in the square bracket
#to get one element from a particular row and a particular column.
arr[0,2]

21.#You can slice rows and columns ;array_name[s_row:e_row,s_col:e_col]
arr=np.array([[10,20,30,40],[1,2,3,4],[5,6,7,8],[3,4,5,6]])
arr

#array([[10, 20, 30, 40],
#       [ 1,  2,  3,  4],
#       [ 5,  6,  7,  8],
#       [ 3,  4,  5,  6]])
#i want 3,4 and 7,8
arr[1:3,2:4]
#OR
#arr[1:3,2:]

#the rows starting from index 1 to rows ending at index 3 (exclusive, means excluding 3)
#i.e. row 1 and row 2, columns starting from index 2 and ending at index 4 (exclusive) 
#i.e. column 2 and column 3.

22.#Negative Indexing
#*positive mein opar row ka number first,ub bhe opar row ka number phala
arr[-3:-1,-2:]
*arr[-3:-1,-2:]

23.#Striding
#Striding - The steps to be taken while moving in a direction
#Whenever you are slicing any list or array or string in Python
#There are 3 things to pass [start index: End index :Stride]
#Stride :the steps you want to jump
arr=np.array([[10,20,30,40],[1,2,3,4],[5,6,7,8],[3,4,5,6]])
arr
arr[0:4:3]
#OR
arr[0::3]

24.arr=np.arange(10)
arr
arr.shape

25.#2D Array Numpy
*arr2d_1= np.arange(1,17)#1-16
arr2d = np.arange(16).reshape(4,4)
arr2d
arr2d = np.arange(64).reshape(8,8)
arr2d
#Indexing n Slicing
#arr2d[3,4] Ans 28

array_name[row,col]>>>> array_name[s_row:e_row,s_col:e_col]

arr2d[6:7,6:7]
arr2d[3:6,2:6]
arr2d[:,6:]
arr2d[:,1] #that column on 1 index;arr like 1d?
arr2d[:,1:2]# arr like 2d ke form mein?
arr2d[:,1:]
arr2d[:,::-1]#?
arr2d[3:4, 1:]

26.#Array 3D
arr3d = np.arange(50).reshape(2,5,5)# depth, row, column
arr3d
arr3d[1:2,3:4,1:3] Ans : array([[[41, 42]]])

27.a = np.hstack([arr2d_1,arr2d_2])
a
# function is used to stack the sequence of 
#input arrays horizontally (i.e. column wise) to make a single array.Concatenate

28.a = np.hstack([arr2d_1,arr2d_2])
a
# function is used to stack the sequence of 
#input arrays horizontally (i.e. column wise) to make a single array.Concatenate

29.a = np.vstack([arr2d_1,arr2d_2])
a
#concatenate vertical wise

30.#hsplit
arr_new=np.arange(12).reshape(3,4)
arr_new
#np.hsplit(arr_new,2)
#function split an array into multiple sub-arrays horizontally (column-wise).
np.vsplit(arr_new,3)
#vertically

31.#random.randint
#is one of the function for doing random sampling in numpy. It returns an array of
#specified shape and fills it with random integers from low (inclusive) to high (exclusive), 
#i.e. in the interval [low, high).
i)a = np.random.randint(10, size=(5, 3))
a
ii)arr2d = np.random.randint(5,10,(5,5))
arr2d
# 5=here,start with 5 and 10=n-10

32.Condition apply on random.randint
arr2d>5
arr2d[arr2d>5]
arr2d[(arr2d>5) & (arr2d<8)]
arr2d[(arr2d>5) & (arr2d%2==0)]
arr2d[(arr2d>5) | (arr2d%2==0)]

33.#np.where()
#function returns the elements in an input array where the given condition is satisfied.
np.where(arr2d>5,9,arr2d)
#where >5 ,n/9 put where condition is true,can put 9 ,0 ,1 anynumber

34.# masking or condition based data selection
a[a>5]

35.import pandas as pd

36.read data
data=pd.read_csv("car_data.csv")
data # will also show total no of rows n columns
sales=pd.read_excel("SaleData.xlsx")
sales

37.call element of any column
data[data.name=='Hyundai Santro Xing XO eRLX Euro III']

38.[{a,a*2}  for a in range(10)]

39.[{a: a.upper()} for a in "saulat"]

40.#Concatenating Arrays
import numpy as np
arr2d_a = np.arange(25).reshape(5,5)
arr2d_b = np.arange(25,50).reshape(5,5)
#from 25 to 49
#both array should be same size,row n column
arr2d_a
arr2d_b

41.merged_array = np.concatenate([arr2d_a,arr2d_b])
merged_array
#horizontal add

42.merged_array = np.concatenate([arr2d_a,arr2d_b],axis=1)
merged_array
#horizontal add axis=1 ==== layta
#vertical add axis=0 ===== khara
#merged_array = np.concatenate([arr2d_a,arr2d_b],axis=0)
merged_array.shape #ans (5, 10)

43.newArray= np.split(arr2d_c,2,axis=0)
newArray
#split the array in 2 sub=arrays in horizonatally ,layta howa

44.newArray= np.split(arr2d_c,2,axis=1)
newArray
#split the array in 2 sub=arrays in vertical ,khara howa

45.#split the arrays in between variables
teri,meri=[[1,2,3],[4,5,6]]
teri
meri

46.A,B= np.split(arr2d_c,2,axis=1)
B

47.arr2d_e=np.arange(64).reshape(8,8)
a,b,c,d=np.split(arr2d_e,4,axis=1)
d

48.ones_like
a = np.array([1,2,3,4,5,6])
np.ones_like(a)

49.#full and fill
np.full(10,5)
#no of times ,wo number lekh du
#10 times ,5 likh du
np.full((5,5), fill_value=10,)
# but yahan matlab size 5 row ,5 column and fill with value 10

50.#numpy.empty() function
#The numpy.empty() function is used to create a new array of given shape and type, 
#without initializing entries. It is typically used for large arrays when performance is critical
#* and the values will be filled in later.
np.empty((4,4))

51.#Identity MAtrix
#An identity matrix is a square matrix in which all the elements of principal diagonals are one,
#and all other elements are zeros. I
np.identity(5)

52.#np.eye(5,2)
np.eye(5)

53.s1 = pd.Series([10,12,14,20,22,24])
s1
#print(type(s1))
#s1.size Ans 6
#s1.shape Ans(6,)
#s1[3]

54.s1.index
#The index property returns the index information of the DataFrame. The index information contains
#the labels of the rows. If the rows has NOT named indexes, 
#the index property returns a RangeIndex object with the start, stop, and step values.

#* eg if there is a file tu us ke series bata dy ge ka 0 sai start and eg 800(total data) 
#pr finish with 1 step
#agar agar index dia hota tu s1.index krna pr index ke values(like Alo ya phr 0) ate
Ans:RangeIndex(start=0, stop=6, step=1)
    
52.s1.values
Ans:array([10, 12, 14, 20, 22, 24], dtype=int64)
    
53.s1 = pd.Series([10,12,14,20,22,24], index=["Anday", "Burger", "Apples","Mangoes", "Alo", "Tomato"])
s1
#index ka barabar jo du ga wo serial no pr a jaya ga
s1["Anday"]
#Ans 10

54.s1[2:5]
s1["Apples":"Tomato"]


55.
#np.nan
#In Python,NumPy NAN stands for not a number;which are numerical values that are missing values in an array

56.#Retrieve of Value:Labels,integer indices

57.#isnull()
#Is NULL function pandas?
#Detect missing values for an array,indicates whether values are missing.
#Returns a Boolean value 
s1.isnull()
s2 = pd.Series([6,12,18,24,30,12,24, np.nan], index=['Alo', 'Mattar','Gajar', 'Moli','Tinda', 'Palak', 'Tamator', 'EMpty'])
s2
s2.isnull()# Ans True where Nan
#*index'empty' krna pr np.nan ,true aya ,warna na true na false dy raha tha

58.#converting dictionary into data frame 
#Creating a python dictionary

dictionary = {'roll':[1,2,3,4,5,6,7,8,9,10],
                      'name':['atif','mohid','bilal', 'uamir', 'dawood', 'ali', 'zohaib', 'nasir', 'shahid','imran'],
                      'course':['Python', 'Web','GD', 'Flutter', np.nan,'Web', "Python", 'GD', "Python", "Flutter"],
                      'Score':[90,45,87,67,30,49,48,np.nan,100,89],
                      'Result':['Pass', 'Fail', 'Pass', 'Pass' ,'Fail', 'Fail', 'Fail', 'Pass', 'Pass', 'Pass']} 

data=pd.DataFrame(dictionary)
data

59.# Retriveing a single columns(series) from data frame
data['Score']
#*A pandas Series is 1-dimensional and only the number of rows is returned. represent []
#*Althought its a data frame,we choose frm data frame but choose onrow so it is 1d / series

60.# A column from a data frame is a series. 
type(data['Score']) #Ans:pandas.core.series.Series

61.# selecting more than one column from a data frame 
type(data[["Score","Result"]])
#*The inner square brackets define a Python list with column names, whereas the outer brackets 
#are used to select the data from a pandas DataFrame as seen in the previous example.
#represent [[]]

62.# adding a new colums in current data frame
data['Class Day']=['Monday', 'Sunday', 'Sunday', 'Sunday', 'Monday', 'Monday', 'Friday', 'Friday', 'Sunday', 'Thursday']
data
#like mostly similar to add key in dictionary ,or something add in list
#i make but deleted percentage column but still shown??

63.# selecting all data but providing a new sequence of columns
data[['roll', 'name', 'Class Day', 'course', 'Score', 'Result']] 

64.# returns column names 
data.columns

65.# overwrting the old column list with a NEW LIST OF column names
data.columns = ['roll', 'name', 'course', 'score', 'result', 'class_day','Percentage']
data

66.#inplace=True
#Using the inplace=True keyword in a pandas method changes the default behaviour 
#such that the operation on the dataframe doesn’t return anything, 
#it instead ‘modifies the underlying data’ (more on that later). 
#It mutates/tabdeel the actual object which you apply it to.
#will now see the modified version of the data — not the original.
#Imagine having an ice-cream, it’s frozen, but then you want to melt it. If you use inplace=True you change the state of the object. You can’t get your unmelted ice-cream back.

#inplace=False
#Alternatively, when using inplace=False (which is the default behaviour) 
#the dataframe operation returns a copy of the dataframe, leaving the original data intact

67.# Rename the columns
#there is a method in df that renames(the columns) .rename    and inplace=True
data.rename(columns={'class_day':'classday'},inplace=True)
data

68.# returns max value from provided column .max()
data.score.max()

69.# checks if there is NAN value in column .isnull()
data.score.isnull() # Ans Boolen

70.#us null wala ka data du
data[data.score.isnull()]

71.#sum()
#sum kara ga ka ketna isnull hein column score mein
data.score.isnull().sum()

72 #isnull in different ways
data.isnull().sum() #Ans course 1 ,source 1 pora data mein jahan jahan NaN ho ga ,
#us column mein total Nan count kr dy ga
roll          0
name          0
course        1
score         1
result        0
class_day     0
Percentage    0
dtype: int64
#data.course.isnull().sum()# Ans 1
#data.course.isnull() # course ke pori row mein boolean apply ,jahan Nan wahan True show kara ga,
#warna false
#data[data.isnull()] #all data Nan ho gaya ,mujha chahya tha course ns core ka data ?

73.#max value ka index dy ga .argmax()
data.score.argmax()

74.data.score.mean()

75.Standard deviation .std()
data.score.std()

76.variance .var()
data.score.var()

77.unique()
#course ke row ke all values without duplicate
data.course.unique()

78.value_counts()
# ya courses ketna students na lia howa hein
data.course.value_counts()

79.sales.Region
i)sales.Region.isnull().sum()
ii)sales.Region.unique()
iii)sales.Region.value_counts()

80.values 
#The values property returns all values in the DataFrame.
#The return value is a 2-dimensional array with one array for each row.
sales.Item.values

81.sales.values
#Pandas DataFrame.values attribute return a Numpy representation of the given DataFrame.

82.# .head()
#The head() method returns the first 5 rows if a number is not specified
sales.head()
#sales.head(10)

83.#.sum()
#sum of the row
sales.Sale_amt.sum()

84.#.max()
#highest value
sales.Sale_amt.max()

85.sales[['Manager','Region']]
#all data of Manager n Region

86.sales[sales.Sale_amt==sales.Sale_amt.max()][['Manager','Region']]
*#sales.Sale_amt==sales.Sale_amt.max() Ans max value True ,others False

87.sales[sales.SalesMan=="Alexander"]['Sale_amt'].sum()
#phala SalesMan==Alexander ko dekho ,agar condition true ho jaya ,
#tu Alexandar us ka sale_amt ka data nekalo,agar ak sa ziada alexandar ke sales a rahe ,tu us ke
#sale ka sum kr du/akk sai ziada alexandar a raha tu sub ke sale ka sum kr du

88.sales[sales.OrderDate<='2018-03-31']['Sale_amt'].sum()

89.#Importing Modules
import numpy as np
import pandas as pd

90.header=0 
#means ,bata raha ka data mein jo phale row hein.column names hein wo heading hai,wo data ka
#part nhe hein;#header=o lekhna nhe parta,kuu ka wo bydefault zero hota hai

91.#headerNone 
#agar header =none kr dia..tu ya phale column names wale row bhe data ka part bun jaya ge
#,us ke jaga 0,1,2,3 default index mein chala gaya

92.#sheet name
df=pd.read_excel("SaleData.xlsx",sheet_name=1)
#jub hum koe excel sheet open krta us mein bohat sari sheets hote hain,wo 0 index leta,ka phale sheet
#agar phale sheet nhe tu phr index mention krna parta hai

93.df=pd.read_excel("SaleData.xlsx",index_col="OrderDate")
df
#already agar sheet mein serial no hein.tu hum khata apna numbers na banao,
#hamara wala column ko as a index use kr li
#ya agar serial no hai.tu hamara serial number ko index bana lu
#LAKIN
#ub orderdate part of data nhe raha..ub wo us ko index treat kara ga;where df is data frame

94.#Selecting a particular column from data
df['Item']

95. usecols=[]   #Selecting a more then one column from data

#*agar humara pass 200 columns or hamara kam ka sirf 4 coulmn tu hum es tarha sirf 4 column
#ka data ly sakta hein
#df[['Region', 'Manager', 'Item', 'Units']]
#LAKIN
#es mein problem hai ka mujha sara df ka data load krna para ,ub wo ketna mb,gb ka howa
#*tu mein na us sai kaha ka pora data load he na karu df[['Region', 'Manager', 'Item', 'Units']]
#*jub file read kr raha hu us wakt he column ly lu
df=pd.read_excel("SaleData.xlsx",usecols=["Region","SalesMan","Sale_amt"])
df
#hum index_col wale S.no ya dateorder ke list bhe call kr sakta usecols mein
#es tarha hamari memory n Ram bhe azad raha ge,kese ka ram kam hu ya memory mein already bohat data
#hu ,aisa he bela waja etna data load kr lia jaya,jis ka kam bhe koe nhe
#speed slow ho jaya kia fayda;kuu ka ya sara data hamara Ram pr chal raha hai,tu load kam raha ga

96.#Selecting more then one column
df=pd.read_excel("SaleData.xlsx",index_col="OrderDate")
df
df[["Region","Manager","Item","Units"]]

97. .loc #SLICING of Columns: 

#slice means copy
df2=df.loc[:,["Region","Unit_price"]] # giving error because (necha detail)
#arr[1:3,2:4] row n column both bata rha,ka us ka beach ka data
#hum deta tha (start of row:end of row,start of column:end of column)
#df mein hum na column tu bata dia,ya nhe bataya ka row ketne select krne hein

#ya sir na kaha bayd mein dekhta hein
df2
# make a variable then dataname with.loc and then : with comma in first[:,]

98.# Adding a Columns to existing data also using import math and math.sqrt() and round()/withdf
#data['Class Day']=['Monday', 'Sunday']
#Lakin
#mujha 44 value/items add krna hu ga otherwise error a jaya ga,us ka lia mein
#list comprehension laga deta hu
#**List Conprehension
#  Output                     Collection                   Condition
#  x+1                        for x in range(5)            if x%2 == 0
#  DO this                    for this Collection          in this Situation
#List comprehension is an easy to read, compact, and elegant way of creating a list
#from any existing iterable object. Basically, it's a simpler way to create a new list 
#from the values in a list you already have. It is generally a single line of code enclosed 
#in square brackets
# for a in range(44) 44 tuk chahya number (note:45 lekh ga tu 44 tuk chala ga,so it has been(45))
# a ko start mein bhe rakh dia..a ko transformation kr dia
#maths ka function import kr lia
#then method.sqrt(a) jo bhe ake value a rahe us ka square root nekal kr es mein rakh dya
#ya sub kia hum na items lena ka lia
df=pd.read_excel("SaleData.xlsx")
df
import math
df['falto_col']=[math.sqrt(a) for a in range(45)]
df.round()
#ub df mein ya naya data add ho gaya,jis ka name hai falto_col

99.# add tax column
df['Tax_Applied']=[(a* .10) for a in df['Sale_amt']]
df.round()
#hum na range ke jaga column select kia,jis ka tax nekalna hai,a ko multiply kr dia 10/100 or .10

100.# Delete Column del
del df["falto_col"]
df
#undo nhe hota,memory sai delete

101. .drop()
#akk sai ziada column bhe delete kr sakta,list bana kr 
#ya phr range dyne para ge
#phala kese or variable mein df ke list copy kr lu
df1=df.copy()
df1
df3 = df.drop(columns=["Region","Unit_price"])
df3

102. loc and iloc   Slicing column and Row   (like arr[1:3,2:4])
#Selecting Rows from data  loc and iloc (ub row and column ke slicing like arr[1:3,2:4])
# Delete Row and add new record in row#ub tuk column add and delete kia(row next cells mein)

#*We have two modes of indexing 
#Label : Header mein label chal raha
#int indices :row mein index
#jis ke waja sai column slicing mein error
#es ka solution loc and iloc
#loc  == labels        : matlab wo samjh jaya ga ka labels hein, jo banda  slice lekh raha hai
#wo mujha labels provide kr raha hai
#iloc == int indices , iloc mein slice kru ga,tu wo samjh jaya ga int indices ke bayt kr raha hai
#means location based chalo

#df1[1:20,'Region':'SalesMan'] Ans error
#df1

#loc
#select kia row1 sai ly kr row 20 matlab 20 record tuk ka data
#* error bc akk taraf int indices chal raha ,dosri taraf label,conflict a raha
df1.loc[1:20,'Region':'SalesMan']
#means ub location based chalo

#iloc
#df1.iloc[1:20,'Region':'SalesMan'] Ans error
#kuu ka region and sales man integer base nhe hein..so in ke integer location dyne para ge
df1.iloc[1:20,1:4]
#n-1
#* ub wo labels ko nhe dekh raha hai,proper column and row number wise chal raha hai
#pechle class mein parha tha..label ke surat mein aya ge,int ke surat mein nhe aya ge??check last video
#label see in last class ,this video confusion at47:50
#*loc label ke buneyad pr chala ga tu akhari index shamil hota hai,int ke buneyad pr chala ga
#tu akhari index shamil nhe hota hai

#es tarha sai ub row ke bhe slicing kr sakta

103.# FANCY Indexing

df1.loc[[12,4,16,8,10],['Item','Unit_price']]
#apni tarteeb ka hisab sai row dy dee..row mein ya lya ana or column mein sai ya ly ana
#jis tarteeb mein dil chah raha ,waisa utha lu...item ko bayd mein bhe kr sakta

104.#Now add Row
#numPy mein tu append kr dia krta tha
#2 number add ho jata bc un ke type same number hote,ese tarha 2 list add ho jate bc un ke type class
#same hote,
#agar dataframe ka undar koe record add krna tu wo bhe data frame he hona chahya
#record=pd.DataFrame({"OrderDate":"NaN","Manager":"Naqv","SalesMan":"SYed"},index=[2])

#akk farzi record lia,key and value bana lee
#index dy dia.ka index 2 pr para howa hai record
# ** DataFrame es lia banaya kuu ka dataframe ka undar dataframe hee add ho sakta hai
# df1.add(record.axis=rows) error timestamp ka
#timestamp error a raha, es lia
#axis=rows means record add krna hai df1 ,lakin record kia hai,row hai ya column hai
#find timestamp ??order date mein date time dala,us ke type string nhe ,date time hone chahya

#tu opar sai record slice kr lu
record =df1.iloc[0:1,:]
#record['Region']="West"
#0 row or us ka sara columns utha lu
#agar record ko add krna sai phala change kr lein tu

#df1.add(record,axis=rows) #areka yahe hai,bs data time ka error a raha

#so hum na dekha column bhe add kr sakta,row bhe add kr sakta,column bhe delete kr sakta,row bhe
#delete kr sakta

105.#EDA:Exploratary Data Analysis
#First, data analyize called EDA#akk akk column ko explore krna parta #explore krna ka bayd 
#data cleansing
#agar data proper nhe hu ga tu un pr jo assumpition ya decision making ho ge wo bhe sahi nhe hu ga
#bayz dafa data kharab nhe hota,bayz dafa data us tarha nhe hota,jis tarha humyn chahya hota hai

106.car_data.shape
#hamara pass 892 record hein and 6 column
#sub sai phala yahe check krta ka data ahi ketna
# data ka head nekal leta hein,shuru ka 5 record
car_data.head()

107.# .tail()
#last ka 5 records
car_data.tail()
car_data.columns

108.# info()
#sub sai important function jo data ko khol kr rakh deta hai
car_data.info()
#name non-null values=892 ,jo proper hein empty nhe hein,es ka matlab name mein koe cheaz missing
#nhe hai,pora pora name lekha howa hein
#***es ke type object,,jub object ke bayt ho ge es ka matlab STRING hai

#kmsdriven and fuel ka record missing hein
#ketna load hai memory pr 41.9 kb
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 892 entries, 0 to 891
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   name        892 non-null    object
 1   company     892 non-null    object
 2   year        892 non-null    object
 3   Price       892 non-null    object
 4   kms_driven  840 non-null    object
 5   fuel_type   837 non-null    object
dtypes: object(6)
memory usage: 41.9+ KB
    
109.# Check Type and Del OR fill
#1.phala sawal ka hamara pass jo data hai us ke type valid hai ka nhe hai
#name ,company object heak
#year ya tu integer hona chahya ya datetime hona chahya eg agar mujha malom krna ka ya car
#ketna sal porani hai tu mujha date sai minud krna para ga
#paisa bhe integer hna chaya
#km bhe int
#fuel type object theak

#es ka matlab type ka masla hain

#2
#ub data ke quality ko check krna ka lia,check kru ga ka missing data ketna hai
#car_data.isnull.sum()

#Big Question : en missing record ka mein kia karu,either delete or either full
#business logic kia hai us ke base pr deicision lia jata hai
#eg problem in hand..agar mujha data ly kr speicific cars ke price malom krne ,tu ya data already
#kam hein,humyn further data loose nhe krna chahya
#eg ub agae eg 2 lac record hota,un mein sai 2k ya 3k ,kam ho jata tu issue na hota
#so deicion based on business logic

110.#fillna 
#missing data  fill
car_data.fillna("datamissing")

111.#dropna 
#missing data  drop()
car_data.dropna()
#LAKIN
#akk problem aya ge

112. #Change in Memory inplace=True OR save in new variable 
car_data.info()
#es ka matlab data memory mein change nhe howa
# ub ya tu new variable mein save ya phr bracket mein ja kr inplace true kr du

113.#inplace=True means original mein ja kr apply kr du
car_data.dropna(inplace=True)
car_data
#*pori row delete kr dee..warna threshhold bhe laga sakta hein
car_data.info()
car_data.isnull().sum()

114. drop_duplicates #Duplicated Records duplicated and drop_duplicates 
#* hum aisa bhe kra sakta hein ka agar pora ka pora column same hein tu duplicate samjhu
#ya 50 mein sai sirf 3 record same tu duplicate samjhu
1.#car_data.duplicated() # es tahra krna sai True ,False aya ga, sum() lagana chahya
2.#car_data[car_data.duplicated()] #pr duplicate record ka complete data
3.#car_data.duplicated().sum() #es tarha total bata dy ga ketna duplicate hein

1.#bydefault lekha howakeep:dropkeep=first
#means first duplicate ko rakho,us ka bayd jo aya ura du
2.#by default ignore index:bool=false
#duplicate drop krna pr jo index ke jaga bache..necha wala index ko opar ly au

car_data.duplicated().sum()
#92 records copy hein
car_data.drop_duplicates(inplace=True)
car_data
#* abhe sub kam Ram ,jupyter pr chal raha hai..excel file mein koe change nhe a raha
car_data.info()
#ub check krta ketna data bacha hai

115.# Now check data type
#data type
#data clean ho gaya,missing and duplicate value sai,ub data type ka opar ata hein
#object ko check krna sai phala abhe hum name ka colum ko check kr raha,koe issue tu nhe es mein
car_data.name

116.
0.#This data is object,object means string
1.#1 column so pd series hoe.pora name series mein a gaya column ka,so index apply howa,
#index slice ho gaya,car_data.name[0][:3]
2.#split : split a string in to list of strings eg name syed saulat ---['syed','saulat']
#etna bara name,es ko chote krta hein
3.#LAKIN slipt ,series #*ka function nhe hai,string ka hai es lia str.lekha.
4.#*ub sawal ya ka kia series,string bun sakte hai,series tu bare sari see list hote hai
#*wo series kaisa bana ge,tu yad rakhna ya vectorized operations hai,jub series ka opar
#*loop chala ga ,ya series pr koe operation hota hai tu wo hur ak pr ho jata ha
#** name series hai but es ka undar string hai,tu loop nhe chalta,loop auto lag jata hai
#car_data.name.str,tu ya akk akk value ko string banaya ga,means series mein sai jo value ate 
#raha ge us ko string banaya ga.str sai
5.#* jub string ,split hota hai tu badla mein list mel jate hai
#ub es pori list mein 0 sai 3 utha lu,
6.#** lakin chuka ya overall series hai tu,car_data.name ,tu series mein sai tu aisa he
#utha gaya name 0 name1 name 3 ,slice kara ga
7.#phr es ko dobara string krna para ga and then slice , .str[0:3]
8.#ub phr pori series result mein aee hai,ub join krna jayn ga tu,series ka pass join ka method he nhe hai
#es lia phr sai string bana kr join kr lein,.str.join()
#** note join and slit (" space")space pr krna hai means space dena hai" "  ka beach mein
#*slice galat bhe lekh dein tu error nhe ata.eg 5 number hein 5000 bhe lekh du

car_data.name.dtype #Ans dtype('O')
#datatype object ,means string
#dtype object but akk series hai bc akk column 1 dimension

#car_data.name[:3] #Ans ,3 rows select kr raha hai
#hum na index dia 0 to 3
#3 rows select kr raha hai,kuu ka ya series bana howa hai,akk column hai es lia eg 
#[name1,name2,name3/index 0,1,2] or hum na row mein chalna hai
car_data.name[0][:3] #Ans Hyu ,string hai index slice ho gaya; 0index pr name ko 0 sai 3 tuk slice kru

#Split :- Splitting Pandas dataframe column values can be done using the split() method. 
#The split() method splits a string into a list of strings based on a specified separator.
Welcome to the Jungle-----['welcome', 'to', 'the', 'jungle']

#**split hona ka bayd list bante hai
#*ya data ak object hai,object means string,slipt apply ho jaya ga,LAKIN slipt ,series
#*ka function nhe hai,string ka hai es lia str.lekha.
#*ub sawal ya ka kia series,string bun sakte hai,series tu bare sari see list hote hai
#*wo series kaisa bana ge,tu yad rakhna ya vectorized operations hai,jub series ka opar
#*loop chala ga ,ya series pr koe operation hota hai tu wo hur ak pr ho jata hai
#eg jub array bane ,2 sai multpily kia tu sb 2 sai multiply
#** name series hai but es ka undar string hai,tu loop nhe chalta,loop auto lag jata hai
#car_data.name.str,tu ya akk akk value ko string banaya ga,means series mein sai jo value ate 
#raha ge us ko string banaya ga.str sai
#* jub string ,split hota hai tu badla mein list mel jate hai
#ub es pori list mein 0 sai 3 utha lu,
#** lakin chuka ya overall series hai tu,car_data.name ,tu series mein sai tu aisa he
#utha gaya name 0 name1 name 3 ,slice kara ga
#phr es ko dobara string krna para ga and then slice , .str[0:3]
#ub phr pori series result mein aee hai,ub join krna jayn ga tu,series ka pass join ka method he nhe hai
#es lia phr sai string bana kr join kr lein,.str.join()
#** note join and slit (" space")space pr krna hai means space dena hai" "  ka beach mein
#*slice galat bhe lekh dein tu error nhe ata.eg 5 number hein 5000 bhe lekh du


#*split series ka function nhe hai,string ka function hai
#ub sawal ya ka ya series ,kia sb pr string ho jaya ga..tu yad rakhna ya vecotrized operaion
#jaisa phala loop mein simple tareka sai howa ya concate mein simple way sai howa
#car_data.name.str.split()[0][0:3].str.join('') # error a raha Sir sai but tareeka kuch ese tarha sai
#list mein name a gaya and then us ko join
car_data.name.str.split()
#pora data column ka split kr dia
car_data.name.str.split().str[:3]
#ub es ko slice kr lia,means sara column ka name slice ho gaya,

#*****car_data sai bola name ka column ly kr au,wo series tha,us ko string kia,us ko split kia
#wo list bun gaya,us ko again list sai string banaya and slice kr dia
#car_data.name.str.split().[:3]
# krna pr hamari data chota ho gaya 0 sai 2 tuk..humyn tu row mein chahya
car_data.name.str.split().str[:3]
#*jub list ko bola string ho jau,tu ub us ke akk ak entry pr apply ho gaya slice eg index
#kuu ka vecotized operations hai

#Vectorized operations that allow you to apply a function or an operation to multiple elements 
#of an array, a vector, or a data frame at once, instead of using loops.

#car_data.name.str.split().str[:3].join('') #error bc list mein join ka function nhe
car_data.name.str.split().str[:3].str.join('')
#tu phr es ko again str dia,str.join
#ub es ko save kr du car_data.name = 
#*agar car_data= kia tu pora data ,akk coulmn ho jaya ga
car_data.name=car_data.name.str.split().str[:3].str.join('')
car_data
#name ke row ke type series sai string ho gae
# (Need to Understand)

117.# astype
#year type object to Integer
#year ke type a rahe object ,es ko change krta
car_data.year.dtype #Ans O

car_data.year.astype('int')
#ub es ko update kr deta hein car_data.year mein
car_data.year=car_data.year.astype('int')
car_data.year
#note :shuru mein es data mein string etc sub kuch add tha name etc..hum na start mein drop kia
#tu luckly sub wrong entries drop ho gae

118.#str.isnumeric()  and use of tilde ~
#The isnumeric() method returns True if all the characters are numeric (0-9), otherwise False.
#car_data.year.unique()
#start mein jub drop nhe kia tha.hur tarha ka type ke value eg name etc
#tu hum sirf interger value mangwa sakta hein

#car_data.year.str.isnumeric() #Ans False True
#sara data utha lu

car_data[car_data.year.str.isnumeric()]
#ub ya string nhe tu es lia error
#** agar tilde laga du i.e ~ ,tu it means ka jahan jahan true wo nhe lena.ulta kara ga
#yahan pr matlaba jahan jahan numeric wo nhe lena
car_data[~car_data.year.str.isnumeric()]

119.value_counts()
car_data.Price.value_counts()
#value.count sai ,count batata ketne bar aee hein

120.~ or !=
car_data[~car_data.Price=="Ask For Price"]
OR 
car_data[car_data.Price!="Ask For Price"]
#ub jahan ask for price ,us ko drop kr dein ga (string)..zero kara ga tu.eg car ke price zero show kara ga
car_data.Price=="Ask For Price"
#car data.price jahan ask for price lekha ho,us ko ~ nhe lena, sath es pora ko masking 
#mein dal dia [~car_data.Price=="Ask For Price"]
#us ka data du car_data[~car_data.Price=="Ask For Price"]
#car_data[~car_data.Price=="Ask For Price"]
#OR if without tilde ~
car_data[car_data.Price!="Ask For Price"]

121. #Replace comma with nothing to convert Object into FLoat
#price ke string value convert into int/float but comma in value

#Price ke type object
#es ke agar simply astype sai change kara ga float mein ,tu ya int nhe hai ya tu string hai as 
#its object

#Note
#*agar int("2300") 
#ya string ,int mein convert ho jaya ga

#LAKIN
#agar int(23,00) #comma hu tu ya nhe ho ga

#*tu phala es ka cooma dur krna hai

car_data.Price.str.replace(",","").astype(float)
#str kae value ko replace kr du,kes ko replace kr du,comma ko,kes sai replace kr du,kese sai nhe
#"" , or jo quotation rha ga,value, us ko float mein convert kr du
car_data.Price=car_data.Price.str.replace(",","").astype(float)

#phala sahi output dee car_data.Price = krna ka bayd error dia

122.car_data.kms_driven.str.replace(" kms","").str.replace(",","").astype(float)
#kms driven ko replace kru, space kms sai, kms ,kes sai,nothing sai replace
# or jo buch jaya us mein coomma ko nothing or phr last mein stype float
*car_data.kms_driven=car_data.kms_driven.str.replace(" kms","").str.replace(",","").astype(float)
#update result check krna ka bayd kr raha,warna galat data update ho jaya ga


123. Save Permanent to_csv
car_data.to_csv("cleaned_data.csv")

124.Data Cleaning and Preparation
#Handling missing Data - fill missing data - drop missing data
import pandas as pd
import numpy as np

125.# dropna    fillna     isnull    notnull
#axis=0 means pori row drop kr dyne hai
#axis=1 means pora column drop kr dena hai

126.#isna()
data=pd.read_excel("SaleData1.xlsx")
data

data.isna().sum()
#ketna missing hai maloom kia phala
#tu humyn column wise bata deta hai,kahan ketna missing hein
OrderDate     0
Region        3
Manager       2
SalesMan      1
Item          4
Units         1
Unit_price    3
Sale_amt      1
dtype: int64

127. np.nan
#add column with values NaN
#data ko akk jan bhok kr ak new column deta hein,Extra ka name sai,us mein value nan dy deta hein
data['Extra']=np.nan
data

128.#dataframe.dropna(axis, how, thresh, subset, inplace)

# axis :- Optional, default 0.
#0 and 'index'removes ROWS that contains NULL values
#1 and 'columns' removes COLUMNS that contains NULL values

#how 'all'   'any'

#'all' and any':Optional, default 'any'. Specifies whether to remove the row or column 
#when ALL values are NULL, or if ANY value is NULL.

#thresh   Number
#Optional, Specifies the number of NOT NULL values required to keep the row.

#subset List
#Optional, specifies where to look for NULL values

#inplace	True
#False	Optional, default False. 
#If True: the removing is done on the current DataFrame. 
#If False: returns a copy where the removing is done.

129.#dropna axis=0
#dropna axis=0 means ,wo row jis ka undar NaN ho ga,wo drop ho jaya ge
data.dropna()
#sub row delete ho gae..kuu ka ak column aisa laga dia jis ka akhir mein sb NaN hai
#inplace: ya permanent delete nhe howa..kuu ka inplace abhe nhe kia tha

130.#dropna axis=1
data.dropna(axis=1)
#ub ya masla ho gaya,jis mein ak NaN tha..us ko bhe ura dia.halaka hamra khayal mein sirf extra ko
#uraya ga

131.#how='all' how ='any'
#data.dropna(axis=1 ,how='all')
#how='all' all nhe urana 
data.dropna(axis=1 ,how='all')
#extra ko ura dia,agar any krta tu sb ko ura deta;jis mein all Nan hu; any=jis kese mein  nan ho

132.# thresh (thresh understand reverse)
data.dropna(axis=1 ,thresh=40)
#thresh :ak value dy de..us ka maltab hota hai,if axis=1 ,column mein 52 ,agar 12 ka kareeb
#values missing hu tu ura du.
#**lakin thresh ka means ulta ,tu hum lekhta ulta..ka agar 40 values true hein tu nhe urana
#eg thresh=41 tu nhe urana
#** matlab jis mein 40 tuk non null value hu ,unha rehna du,unha na urnana
#thresh means urana
data.dropna(axis=1 ,thresh=50)
#es na item ,region and unit+price ura dia..ku ka region mein 49,item 48 and unit price 49
# tu 50 threah tha..ura dia pora column

133. subset
#hum column name define kr dein ga ka es ko dekho,pora data ko nhe

data.dropna(axis=1 ,thresh=50 ,subset=['SalesMan','Item']) #error a raha but ese tarha ho ga
#sir na bhe chour dia

134. fillna
data.fillna('missing')
OR
data.fillna(200)
#abhe simple missing sai fill kr dia,hur jaga missing lekha howa a gaya

135. # Hardcore data fill by using Dictionary
#data.fillna(200)
#ub masla ka hur jaga ,even region etc mein bhe 200 lekha howa ho ga
data.fillna({'OrderDate':'2019-12-31','Region':'Central','Manager':'saulat',
             'SalesMan':'Shahid','Item':'Cell Phone','Units':'100','Unit_price':'225.0',
             'Sale_amt':'63494','Extra':200})
#dictionary bana dee,ka jis coulmn mein jo missing hai wahan ya value dal du,
#region ,central ,ya tu hardcore decision ya stastics 
#ya hum na hardcore decision sai fill kia
#ya true representation of data na hu
#true representation of data ka lia ,statisitics fill krna chahya;calculated fill krna chahya

136. # data fill Statistically OR true representation  USING MODE (for non-numeric value)
data.fillna({'Region':data.Region.mode()[0],'Manager':data.Manager.mode()[0],
             "SalesMan":data.SalesMan.mode()[0],"Item":data.Item.mode()[0],
             "Units":data.Units.mean(),"Unit_price":data.Unit_price.median(),
             "Sale_amt":data.Sale_amt.median(),"Extra":300})

# Mode use kara ga,jo item sub sai ziada bar aya howa hai wo fill kr du ,Nan ke jaga

data.fillna({'Region':data.Region.mode(),})
# matlab region mein kuch missing hai tu us ko fill kr du
#* kaisa fill kru,dictionary ka undar region: ke value mein,data ka undar jau-region ka column
#uthao-or us ka mode nekal du,or jo most repeated value aya mode sai.osa fillna ka zareya fill
#kr du
# **Manager wala column bhe numeric nhe,es lia mode nekal lu
#Mode;aisa bhe ho sakta ka 2 mode value dekha,,jub us na frequency check ke tu ho sakta ,2 logon ke 
#appearance barabar a jaya,saulat bhe 5 dafa aya,naqvi bhe 5 dafa aya,tu phr un mein sai ak
#manually select ke lein
#* Mode wahan dalta jahan non numeric values hote hein

137.  # data fill Statistically OR true representation  USING Mean and Median (numeric value)                     
#Mean: Units numeric hai,es lia average nekala ga,or average nekalta mean sai
#lakin agar data mein variance ziada hota ,outliers hota tu Median nekalta
#Unit_Price mein outliers a raha tu mediana lagaya ga

138. # if multiple modes and result in series (0 Central) convert in string
#Note es na data update nhe kia,,bc ya series ke form mein result la raha(with index)
#,Mode,Median,Mean sb series ke form mein result a raha

#**'Region':data.Region.mode() jub hum na kia tu jawab hai series mein i.e 0 Central
# tu ya 0 Central ,du alag column kaisa fill karyan central mein ya index kaisa fill kara
# **humyn tu string chahya or ya series hai

# ****mode() returns a Series (a type of pandas DataFrame), not a single value.
#This is because there can technically be multiple modes in a dataset. 
#By indexing with [0], you are selecting the first mode in the dataset.
#matlab agar ak column ka data ka 3 mode nekal aya eg Central,South,North ,matlab 
# teenu,5 5 5 bar aya. tu en ka sath index 0 central , index 1 South and index 2 North ho ga
# *tu ap na jo value uthane us ka index dy du ga eg Region':data.Region.mode()[2]

data.fillna({'Region':data.Region.mode()[0],'Manager':data.Manager.mode()[0],
             "SalesMan":data.SalesMan.mode()[0],"Item":data.Item.mode()[0],
             "Units":data.Units.mean(),"Unit_price":data.Unit_price.median(),
             "Sale_amt":data.Sale_amt.median(),"Extra":300})

#ya [0], ya sb alag index pr hein???

#data.Sale_amt.median() en mein numeric value dy raha eg 14400
#* agar datetime ka column hai tu khata hai not a time..warna NaN

139. #Class Task
#a)Download and load the dataset in pandas from
import pandas as pd
data=pd.read_excel('employee.xlsx',index_col='Serial')
data

#b)Write the query that shows how many duplicate records are there?Further fetch all the duplicate records.
#how many duplicate record
data.duplicated().sum()
#show that records
#data.duplicated() #Ans will be in true false
data[data.duplicated()]

#c)	Write the query to find the count of each designation in the data? 
data.Designation.value_counts() #maloon ho ga,deisgnation mein kes position pr ketna log hein

#d)	Remove the duplicate record from the employee data frame.
data.drop_duplicates()
data # es na 3 duplicate nekal dia,phr bhe 18 ka 18 nazar a raha kuu ka inplace nhe kia,
#permanent duplicate remove nhe howa
data.drop_duplicates(inplace=True)
data

#e)	Write the code to fill the missing value of the Salary, Department, Age columns? Discuss your 
#choice of value, like a hard coded value, a mean, median, mode of the column?
data.info()
data.isnull().sum()

data.fillna({'Department':data.Department.mode()[0],'Age':data.Age.mean(),'Salary':data.Salary.median()},inplace=True)
#Hum complete data fill kr sakta hein dictionary bana kr
#chuka department ka name hein.tu mean nhe nekal sakta na median,mode nekal sakta hein
#data mein department mein jao,us ka mode nekala ,us mein series aya ge us ka zero index utha lu
#phr missing hai age mein,us ka mean nekala,,sath mein dekha ka data bohat disburs tu nhe hai
#salary ka median nekalna chahya..phala es ka output dekha,phr us ko inplace kr dia
data

#f)	Write the code to find the average salary of the accounts department
data[data.Department=='Accounts']
#phala account ko target krna hai,department kes ka barabar chahya ,accounts ka
#data[data.Department=='Accounts'] es tarha accounts department ke list select ho gae
#accounts mein ya 3 log kam kr raha hein,manager,office boy,accountant
#ub es mein account ka sub nazar a raha,es ka undar column select kia salary ka
data[data.Department=='Accounts']['Salary']
#ub es salary ka nekalna hai average,means mean nekalna hai,es tarha AC Dept ke avg salary nekal aya ge
data[data.Department=='Accounts']['Salary'].mean()

#g)	What the department and Emp_ID of the manager having the highest salary
#sawal ko samjhu,ak tu employee hona chahya mor employee mein hona chahya manager or sara managers 
#mein us ke sub sai ziada salary hone chahya
data[data.Designation=='Manager']
#ya sara managers uthaya ga phala
data[data.Designation=='Manager']['Salary'].max() #Ans 200000
#sawal pora nhe howa,humyn manager ka name and salary chahya
data[data.Salary==200000.0]
#salary ka column uthaya or wo barabar ho 200000.0 ka
#      OR 
# es sai bhatar lekhna ka tareeka ,max salary ke query ko == karu
# * es ka fayda ya ka agar data mein change ho jaya 2 lac ke jaga 50 lac tu right information mela
#ge
data[data.Salary==data[data.Designation=='Manager']['Salary'].max()]

# data[data.Salary==data[data.Designation=='Manager']['Salary'].max()]['Department','Emp_Id'] #Error

#Error a raha because jub bhe akk sai ziada dein ga tu list bana kr deina ga 
# like [  ['Department','Emp_Id']  ]

data[data.Salary==data[data.Designation=='Manager']['Salary'].max()][['Department','Emp_ID']]

#h)	What is the average age of the Officers in the company?
#so phala age nhe,phala designation.,and designation barabar hone chahya officers ka
#phala sara officers select kr lu
data[data.Designation=='officer']
#ub en ke Age utha lu
data[data.Designation=='officer']['Age']
#ub en ages ka mean utha lu

data[data.Designation=='Officer']['Age'].mean()

#i)	Write the query to show how many employees are working in IT department?
#ya value_counts sai bhe ho sakta,lakin us mein sara department ka employees dekahya ga
data.Department.value_counts()
#sirf count mein IT mein sub deisgnation etc ka count,salary ka count etc
#tu phala tu department ko barabar kr lu IT ka
data[data.Department=="IT"].shape[0] #Ans (7,5) means 7rows and 5 columns,tu mujha sirf row uthane hai
# (Need to Understand)
#OR
data[data.Department=="IT"]['Emp_ID'].count()
#OR

(data.Department=='IT').sum()

# OR best way is below both
len(data[data.Department=='IT'])

# OR
data.Department[data.Department=="IT"].count()

#j)	After cleaning the employee data set, save the data set in csv format in a file
#save krna ka tareka
data.to_excel("cleaned_employee.xlsx")

140.#Note Float ; ordinal numbers type
#*agar sare values integer hein.us mein ak bhe float a kr gera,tu pori series dekhaya ga float
#* ese tarha agar sara integer hein or ak NaN bhe gaee,tu NaN ke waja sai sara float hu jayn ga

#phone number,numbers tu hota hein but wo integer nhe hota,ordinal number nhe hota,nominal numbers
#hota hein,un ke data type rakho object or string
#bohat sara phone number lekha hun ,tu us ko order nhe kr sakta,sort nhe kr sakta,wo numbers hein
#wo number lekha howa integer mein,kia koe phone number 0 sai start dekha raha ho ga,nhe.
#us ke data type rakhta,object ya string

141.# NOW COMPLEX DATA CLEANING
#EXPLORATORY DATA ANALYSIS
#Exploratory data analysis of Housing Data
data=pd.read_csv("Bengaluru_House_Data.csv")
data
data.shape
data.columns
data.sample(10)
#koe bhe 10/random
data.head(10)
#0 -9 start
data.info()
#pora data ke information dy deta hai #all detail
#including non null value,es data mein 13320 means 13320 non null value valid hein
data.area_type.unique()
# idea krta ka area_type mein kia kya hai,4 kes ke type a gaee area_type mein
data.area_type.value_counts()
#kes area mein ketna makan hain,wo a gaya

data.availability.unique()
#data.avaiability ke bhe unique dekh leta hein

data.location.unique()
#mujha sarae location ka name parhna hein but sahe sai nhe parh pa raha,list a rahe
#for loop laga kr print karwa liafor a in data.location.unique():
**** for a in data.location.unique():
    print(a)
#hum yahan names ko chota bhe kr sakta..lakin yahan phase 1 phase 2 lekha howa..koe as such masla 
#nhe hai

142. #         Lambda Function
#i)
result=pd.read_excel('Result.xlsx')
result

#ii)
result=pd.read_excel('Result.xlsx',index_col='Roll')
#ub roll number bhe a raha or index bhe tu index ke jaga pr roll number a jaya ga
result

#iii) Concatenate all subjects
result['total_obt']=result.Python + result.Pandas +result.Numpy+ result.Stats + result.Flask + result.ML
result
#akk total_obt ka column add kia ,us mein hur student ka total numbers add kia

#iiii) Percentage using for loop and round

result['Percentage']=[round((a*100/600),2) for a in result['total_obt']]
#OR
result['Percentage']=round(result['total_obt']/600*100,2)
result
#jo result aya us ko round kr du ,2 figures tuk
#agar % ka sign lagaya gya tu ya value float nahe raha ge

#        ============ Get Percentage by using function n Condition, By Lambda and By Comrephension===========

143.# Get Percentage by using function n Condition / USING ,apply(), By Lambda and By Comrephension

#1st)  Assign GRADE  USING    .apply()

# * Internal loop chala ga .apply() sai akk akk percentage pr

# ub es percentage kee buneyad pr Grade assign karna hein#es ka bohat sai tareeka# akk tu function bana kar
def assign_grade(percentage)
#assign grade ka function banaya or us ko dia percentage
# .apply()
#by condition
def assign_grade(percentage):
    if percentage>=90:
        return "A1"
    elif percentage>=80:
        return "A"
    elif percentage>=70:
        return "B"
    elif percentage>=60:
        return "C"
    elif percentage>=50:
        return "D"
    elif percentage>=40:
        return "A"
    else:
        return "Fail"
    

result['Grade']=result.Percentage.apply(assign_grade)
result
# ya auto internal loop chalta rha ga,akk ak percentage utahaya ga us ka against grade phankta raha ga

144.# By --------- Lambda Function---------------

#ya annoynumous function hota ,es ka name koe nhe hota
# **or ya ose cell mein istemal ho ga,wahan pr he khatam or dosra koe us ko call nhe kr sakta
#hum chahta alag function na banana para ,balka cell he mein nemut jaya
#result['Grade']=result.Percentage.apply()
#result['Grade']=result.Percentage.apply(lambda x:)

#Lambda apply kru,Lambda ka pass jo value aya ge wo variable x mein gera ge
#ub opar wala function ka sara kam yahan ho ga

result['Grade1']=result.Percentage.apply(lambda x: "A1" if x>=90 else "A"if x>=80 else "B" if x>=70 else "C" if x>=60 else "D" if x>=50 else "Fails") 
result

#** agar x>=90 ho jaya tu,,,tu pecha lekhta hein if ka pecha ,here "A1"
# yahan elif nhe chalta ,else if alag chala ga,and "A" if ka pecha

#*Lambda ak aisa function hota hai,ka jahan humyn quick kam krta hota,short kam krna hota ya koe aisa 
#kam krna hota hai which will nt repeat again,ka mujha us kam ke dobara zarorat nhe krne hai ,es lia 
#mein us ka function nhe banana chah raha hu

#logical bayt ya ka hum module base kam kr raha hota hein,un ka undar jo function rakha hota hein wo
#module base kam krta hein,bajaya es ka ka module ko import kru,phr funcion create kru or us ko module
#mein call kru ya implement kru

145. # by List Compreshension 
# same cheaz utha kr list comprehension mein dal du
#by for loop

result['Grade2']=["A1" if x>=90 else "A"if x>=80 else "B" if x>=70 else "C" if x>=60 else "D" if x>=50 else "Fails" for x in result.Percentage] 
result

#first list mein dala
# es pr loop chala, for x in result.Percentage 

#1.result['Grade']=result.Percentage.apply(assign_grade)
result

#2.result['Grade1']=result.Percentage.apply(lambda x: "A1" if x>=90 else "A"if x>=80 else "B" if x>=70 else "C" if x>=60 else "D" if x>=50 else "Fails") 
result

#3.result['Grade2']=["A1" if x>=90 else "A"if x>=80 else "B" if x>=70 else "C" if x>=60 else "D" if x>=50 else "Fails" for x in result.Percentage] 
result

146.# zip
#bund krte hai
# zip eg
# 2 list
a=[1,2,3,4,5,6]
b=[7,8,9,10,11,12]
zip(a,b)
#zip kr du a and b ko
#es object ko cast kar du ,list sai
# list sai type cast kr du
list(zip(a,b))
#jaisa zip chalte hai ak yahan sai ak yahan sai,pair banta jata hai,one one ka pair
#Ans:- [(1, 7), (2, 8), (3, 9), (4, 10), (5, 11), (6, 12)]

147.# Looping Row Wise

# * abhe tuk looping column wise chal rahe thee,pora column pr loop laga raht ha,
#ub student ka reocrd wise check krna hai,hum kara ga row wise
#list comprehension sai bhe kr sakta,Lambda bhe laga sakta ,alag function bhe bana sakta hein
#ub thora sai kam mushkil ,ub check krna ka each paper mein pass hai student ka nhe,ub individual paper mein check krna hai.

[result.iloc[a] for a in range(1)] Ans row with column
# Ans LIKE 
#:[Name           Rauf
# Python           78
# Pandas           78
# Numpy            98
# Stats            67

# 1st ZIP
#[ for Py, Pd, Np, St,Fl,Ml in zip (result.Python,result.Pandas,result.Numpy,result.Stats,result.Flask,result.ML)]

#ub ya zip ho kr aisa ho jaya ge values
# ya zip ho kr es tarha ho jaya ge (78,78,98,67,76,99)
# unzip krna ka lia 
#(a,b,c,d,e,f)=(78,78,98,67,76,99)

#[ for Py, Pd, Np, St,Fl,Ml in zip (result.Python,result.Pandas,result.Numpy,result.Stats,result.Flask,result.ML)]
#tu ya 5 values unzip ho jayn ge Py,Pd,Np,St,Fl,Ml mein
[(Py, Pd, Np, St,Fl,Ml) for Py, Pd, Np, St,Fl,Ml in zip (result.Python,result.Pandas,result.Numpy,result.Stats,result.Flask,result.ML)]
# ub sirf mujha  ya values dekha ga

# ub list ka sath tuple aya ga
#LIKE [(78, 78, 98, 67, 76, 99),
#       (89, 67, 78, 87, 78, 98)]


#2nd COndition

#ub conidtion laga gee,sari values check hu ge,hur ak ka true hona zarori hai
# phala if ke nested condition ka function bana kr check kr leta hein ,taka lekhna asan ho jaya
# NESTED IF 
#NEsted if chala,first true then aga gaya warna else,all condition true 
# *all condition true tu true kr du
def status(marks):
    #marks ka tuple aya ga?
#means tuple ke surat mein jo a mein aya,,akk akk row ka tuple
    Py, Pd, Np, St,Fl,Ml=marks
    #OR
#def status(a)
   # Py, Pd, Np, St,Fl,Ml=a
    #unzip kr dia,ub sara marks =marks
    if Py>=50:
        #pass
        if Pd>=50:
            #pass
            if Np>=50:
                #pass
                if St>=50:
                    #pass
                    if Fl>=50:
                        #pass
                        if Ml>=50:
                            return "Pass" #agar all 5 mein condition pass ho gae tub pass
                        else:
                            return "Fail"
                    else:
                        return "Fail"
                else:
                    return "Fail"
                
            else:
                return "Fail"
        else:
            return "Fail"
    
    else:
        return "Fail"




result['Status']=[status(a) for a in zip (result.Python,result.Pandas,result.Numpy,result.Stats,result.Flask,result.ML)]
# zip ho kr pora tuple aya ga  ,a, mein chala jaya ga sara values
# a ka lia status ka function call kia,akk akk true check howa,then pass,,agar akk flase tu direct fail
result

.#*alag function bana kr condition check

 #         =========================Transforming Data   # Mapping===================================
    
148. # mapping two series    x.map(y)

import pandas as pd
#create two series object to demonstrate Mapping
x=pd.Series({"one":1,"two":2,"three":3})
y=pd.Series({1:"a",2:"b",3:"c"})
# 2 series hein, akk series ke value,dosri series ke keys hein
x                           y                   x.map(y)
one      1             1    a                 one      a
two      2             2    b                 two      b
three    3             3    c                 three    c
dtype: int64         dtype: object            dtype: object

#map values in x to values in y
x.map(y)
# x mein jo values hein un ko y mein map kr dia jaya
# eg x, one   1 ; y, 1  a  so one a  jahan y ka 1 tha us ke value a dal de,map kr dee

149.
s=pd.Series(['cat','cow','dog'])
print(s)
print("Mapping: ")
s.map({"cat":"kitten","cow":"calf"})
# s ke series ko s.map({"cat":"kitten","cow":"calf"}) es dictionary ka sath ma kr du

0    cat              0    kitten
1    cow              1      calf
2    dog              2       NaN         
dtype: object         dtype: object
        
150. # Data Frame Mapping
data=pd.DataFrame({'Country':['Pakistan','Saudia','Turkey','Palestine','Oman'],'Pop':[256,36,85,5,5]})
data
capitals={'Oman':'Muscat','Saudia':'Riyad','Pakistan':'Islamabad',"Turkey":'Ankara'}
#LIKE   
    Country     Pop
0   Pakistan    256

data['Capitals']=data.Country.map(capitals)
data

        Country   Pop   Capitals
0       Pakistan  256   Islamabad
1       Saudia    36    Riyad
2
3.      Palestine  5    NaN

151.
import pandas as pd
***** Practice ths dataframe

df = pd.DataFrame([('carrot', 'red', 1), ('papaya', 'yellow', 0),('mango', 'yellow', 0), ('apple', 'red', 0)], 
columns=['species', 'color', 'type'])
mappings = {'carrot': 'veg','papaya': 'fruit'}

print("Dataframe before Mapping: ")
print(df)
#ya ak data frame banaya tuple ka through

df['type_name'] = df['species'].map(mappings)
print("Dataframe after Mapping: ")
print(df)

#map kr ka new series banata hai
#ya hum na kia ya hai type 1 ,0 a rahe..user ko samjh nhe aya ga,ub hum na user ko batana ka species 
#ke type kia hein

152.data = pd.DataFrame({'food': ['bacon', 'pulled pork', 'bacon','Pastrami', 'corned beef', 'Bacon','pastrami', 'honey ham', 'nova lox'],
'ounces': [4, 3, 12, 6, 7.5, 8, 3, 5, 6]})
data
meat_to_animal = {'bacon': 'pig','pulled pork': 'pig','pastrami': 'cow','corned beef': 'cow','honey ham': 'pig','nova lox': 'salmon'
}

#meat to animal ke dictionary hai,kon sai gosht kes janwar ka hai
#ub es dictionary ko map krna .ka hur meat ke source kia hai

data['Meat_to_animal']=data.food.map(meat_to_animal)
data
        food     ounces   Meat_to_animal
0       bacon    4.0      pig
3       Pastrami 6.0      NaN

#ub opar Pastrami Nan dekha raha,kuu ka ,kuu ka meat to animal ka data mein wo small mein hai pastrami,same bacon
data.food.apply(lambda x:x.lower())
# ub es na auto internal loop chala kr sub ko small kr dia data.food mein
# then es ko data.food mein replace dal du
data

153. # Lamba Practice & Vectorized Operation
#lambda ke aisa he ak pratice
#data.ounces.apply(lambda x: x+0)
#OR
# as its vactorized operation ,we can also write,other then Lamda
#like
#data=data.ounces+20
#data

154.# REPLACING VALUES by Lambda
# Transformation mein kaee jaghoon pr humyn replacing bhe krne pr jate hai
data1 = pd.Series([1., -999., 2., -999., -1000., 3.])
data1
#-999 bohat chote value es ko zero kr du
#ub ak tareka tu Lambda sai kr du,dosra Replacing

#Lambda sai
data1.apply(lambda x:0 if x <=-999 else x )

# x ka pass value ayan ge data ke series sai.
# agar wo ,x, -999 sai bhe chotee hu tu kia karna
# us ko 0 ka barabar kr dena
# warna , else,X he rehna dena

#*jub hum column bolata,tu one by one value nekalta ,loop ke tarha,us mein kamal lambda ka nhe,vectrize 
#operation ka hai,pecha loop chal raha hota hai
#*** tu series ka fayda he yahe hai ka jo vectorize operation perform krta hein ,wo pori series pr
#apply ho jata hai
#list pr apply hai he nhe,apply series ka function hai

#OR By  Replace

data1.replace(-999,0)
#LAKIN
#* es mein problem ya ho ge ka wohe value replace ho ge,1000 wale nhe ho ge


             ===================DISCRETIZATION AND BINNING================

155.     #Binning   .cut()
#Binning
ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32] # Container

#Lets divide these into bins of 18 to 25,26 to 35,36 to 60 and finally 61 and older.TO do so,
# you have to use cut,a function in pandas.

bin=[18,25,35,60,100]
cats=pd.cut(ages,bin)
cats
#cats=category ,wo jo opar hamara pass container data tha ,wo ub categorical data mein convert ho jaya ga

#[(18, 25], (18, 25], (18, 25], (25, 35] ya kia dy raha hai    # Categories
# ya kha raha hai jo phale age hai 20, wo[(18, 25] ke category mein hai,ese tarha 4th age 27
# (25, 35]  ke category mein hai

#length 12 means 12 ages in container 
#Categories 4

#( ] called open and closed intervals
# ** (8 , =it means 8 included
# ** 25] = means 25 not included
# matlab 8 sai shuru ho or 25 ka undar


156.# category codes / clusters  .codes
#category codes
cats.codes
#phale category ko 0 index bol dia,dosri category ko 1 index
# (18, 25] 0 index 
# (25, 35] 1 index and so on
# in machine laguage category called clusters

157.# category codes can be replace by number or name  labels
cats=pd.cut(ages,bin , labels=['Bacha hai','Jawan hai','Old hai','Rub ka pyara'])
cats
pd.value_counts(cats)


#              =================Permutation and Random Sampling=======================
158.
import numpy as np
df = pd.DataFrame(np.arange(5 * 4).reshape((5, 4)))
df
# 5*4 means 20 arange
    0	1	2	3
0	0	1	2	3
1	4	5	6	7
2	8	9	10	11
3	12	13	14	15
4	16	17	18	19

159.#now generate random number
sampler=np.random.permutation(5)
sampler
# 5 es lia lya ka 5 record hein,means 5 rows hein
#*es na koe akk way permute dy dee,jetne ke hum na range de
# ya number apni taraf sai bhe lekh sakta tha,lakin phr create hota biasness
ANs: array([4, 2, 0, 1, 3])
    
160. # take
df.take(sampler)
# data ka undar sai ya wala sampler ly lu
df
# statics mein bohat important hota hai sampling concept,agar sampling theak nhe kr raha tu result
#theak nhe ayn ga

#what is sampling ,random sampling
#one of the method of sampling is Random Sampling
# eg take few students weight out of class,means got few result and apply on all population
#In statistics, sampling allows you to test a hypothesis about the characteristics of a population.
#A sample refers to a smaller, manageable version of a larger group. 
#It is a subset containing the characteristics of a larger population.

161.df.sample(5)

    0	1	2	3
0	0	1	2	3
4	16	17	18	19
1	4	5	6	7
2	8	9	10	11
3	12	13	14	15

               ===============Computing Indicator/DUmmy Variables==================
#encoding of data
#jub bhe hum kese data ko machine sai pass karwata hein,machine 0 ya 1 samjhte hai

162.
data=pd.read_excel('SaleData.xlsx',index_col='OrderDate')
data

163. # Dummy Variables   get_dummies()
#hum dummy value es lia get krta hein ka hamara nominal data ,understand tu machine language convert
# hu ,es tarha ka us ke nominality bhe bakee raha

#jub bhe hum kese data ko machine sai pass karwata hein,machine 0 ya 1 samjhte hai
# interger value tu binary 0 and 1 mein convert ho jaya ge
#string ka kia kara ga,akk jawab tu ya ka hur alphabet ka against akk ST value hote hai,jo number bun 
# jaya ga,jis ko binary mein convert kr dein ga
#agar opar sales wala data ka nominal data ko ST sai number mein convert kr ka binary kr dia tu
#wo numeric ho jaya ga.which is wrong ,humyn agar is data ko encode krna hai
#* es tarha ka wo number bhe bun jaya or es ke nominality bhe qayam raha or string bhe na ho
#es lia hum banata dummy variables
#below is an example

# ** DUmmy data used for Nominal data to change  string in machine language

#see one hot encoding image on google
# see in image
# S.no  Color           Sno   RedColor   Blue COlor    Green COlor
#  0     Red            0      1          0             0
#  1     Blue           1      0          1             0
#  2     Green          2      0          0             1
# 3      Blue           3      0          1             0

# ub ya red ka dummies mel gaya    1 0 0
# ya one hot encode ho gaya
# necha jub Central ho ga tu Central true,East n West False

164.
data.Region.value_counts()

pd.get_dummies(data.Region)
#dummies hasil kru,data,region ka undar hein

           Central  East    West
OrderDate
2018-01-06	False	True	False
2018-01-23	True	False	False

165. # DUmmy data in whole data where there is Nominal/name/noun
# ub pora data mein jahan nominal data us ke dummies
pd.get_dummies(data)

#*#data able to process ho gaya machine model mein process krna ka lia lakin columns barh gaya

           Units	Unit_price	Sale_amt	Region_Central	Region_East	Region_West	 Manager_Douglas	Manager_Hermann	Manager_Martha	Manager_Timothy	...	SalesMan_Michael	SalesMan_Shelli	SalesMan_Sigal	SalesMan_Stephen	SalesMan_Steven	Item_Cell Phone	Item_Desk	Item_Home Theater	Item_Television	Item_Video Games
OrderDate
2018-01-06	95.00	1198.000	113810.00	       False	   True        	False	  False	                    False	  True	

# How it works
# eg sentence ,
# remove punctuation and stop words
# 1st TOkenize into words
# each words has it token,
# remove duplicate words
# then vector eg Saulat eat apple,,tu jub Saulat aya ga tu wo one ho ga ,eat and apple 0 ho ga
# its encoding ,1 word ka lia 40k ka vector eg 40k words

166.
df=pd.DataFrame({'key':['b','a','c','d','e','a'],'data1':range(6)})
df
pd.get_dummies(df['key'])
# see unique values le a,b,c ,d,e 
#us ka token bana
#agar eg 50k workds hota ,tu ak word ka lia 50K ka vector hota,jis mein akk true hota ,bakee sara False

      a	      b	      c     	d	  e
0	False	True	False	False	False
1	True	False	False	False	False
2	False	False	True	False	False
3	False	False	False	True	False
4	False	False	False	False	True
5	True	False	False	False	False

167. # By Loop
df['new']=df['key'].apply(lambda x:1 if x=='a' else 2 if x=='b' else 3 if x=='c' else 4)
# Replace:x mein values aee, agar x== a ka ,tu osa 1 sai replace kr dena warna agar x==a ka 
#barabar na hu tu 2 sai replace kr dena
df
#problem ya hoe ka replace number sai howa..number can add ,can figure out big and small,ese problem
# sai machine ko rukwana hai,nominal mein chota bara nhe hota eg ,mango bara ka apple,ya categories
#hein en ka comparision nhe hota,en ke value ka hota


#*embedded coding,highup level encoding.like chat gtp,voice,using now a daysall tranformation from voice into text into numbers into tokenize
#into vectorization


#              =============================         Data Wrangling            ==================================

#              =============================   Join , Combine and Re-Shape     ==================================

168.
# different sources sai data combine ho raha ya alag ho raha es ko Wrangling khata hein

#akk tu data transformation tha ,jis mein data ka undar ghus kr changes kee,values mein changes ke
#Wrangling mein values change nhe krta,data ke shape change krta hein, 2 dataframes add kr raha hota hein
#kuch filter kr ka data mein sai nekal raha hota hein, 2 data sets ko combine kr raha hota hein
#re-shape kr raha hota hein

# COMBINING AND MERGING DATA SETS
#Data ko apis mein merge krna.ya array ke tarha jo pecha parha ,waisa combine nhe hai
# ya combine hai different kesam ka
#data ke field mein enter ka lia joints ko theak sai parhu
# different sources sai data combine ho raha ya alag ho raha es ko Wrangling khata hein

169.#   pd.concat  axis=0 (by default) / Horizontal  / Increase in Rows ( When rown n COlumns are Equal)

df0=pd.read_excel("test_data (1).xlsx",sheet_name=0)
df1=pd.read_excel("test_data (1).xlsx",sheet_name=1)
df2=pd.read_excel("test_data (1).xlsx",sheet_name=2)

df0
df1
df2

#3 sheets hein excel file mein
# sheet df 0 , df 1 ,df2 rows are same ,but df 0 and df 1 columns same but row different

#sheet 3 mein columns change hein ,sheet 2 and 1 mein same hein
#akk concate ka function mojood hota hai,concate kia krta hai
#object leta hai list form ka undar or un ko concatenate kr deta hai
#concatenate krna ka lia hum na numpy mein dekha tha ka kia cheaz zarori hai
#* ka agr mein horizontally concatenate kr raha hun ,tu rows 4 ya 5 nhe hone chahya,akk extra na rha
#jaya necha ya opar
# * agar vertically concatenate kr raha hu,tu column barabar hona chahya,extra na a jaya

# ub 2 different sources sai aya howa data ko concatenate kr raha hein,column donu ka check kr lia
# ak jaisa hee hein

pd.concat([df0,df1])

#df1,df0 ka necha murge ho gaee
#ya donu horizontal axis ka opar concatenate ho gae
# lakin index repeat ho gaya

# ** jub necha add ho raha hai tu rows mein izafa ho raha hai,axis 0 mein increase ho raha hai
# agar column barh jayn ga tu axis 1 mein increase ho ga

pd.concat([df0,df1])

sales_man_id    sales_man_name         sales_man_city      product_id manager
0	1	        Asad	                Karachi	             123	   Jawed
1	2	        Sumair	                Lahore	             123	   Jawed
2	3	        Farjad	                Karachi	             145	   Najam
3	4	        Hassan	                Lahore	             567	   Najam
0	11	        Ahmed	                Karachi	             123	   Jawed
1	22	        Umer	                Lahore	             123	   Jawed
2	33	        Huzaifa	                Karachi	             145	   Najam

170. #  pd.concat  axis=1  / Vertical  / Increase in Columns  ( When rown n COlumns are Equal)

pd.concat([df0,df1],axis=1)

#axis 1 sai increae kr raha ub
# donu ka 8 records hein,lag jayn ga
#columns barh gaya

    sales_man_id sales_man_name sales_man_city  product_id	manager  sales_man_id  sales_man_name  sales_man_city  product_id	manager
0       1	       Asad	           Karachi	       123	     Jawed	     11	             Ahmed	        Karachi	   123	    Jawed

171. # 2 sheet rows equal but not column equal

pd.concat([df0,df2])

#ub hum df2 ko add kr raha jis ka column kam hein

#NOTE: numpy mein ya allow nhe kr raha tha
#jo column overlap tha wo la lia,
#salesmanid mein region sales and amount nhe tha us ko NaN kr dia
# ak trha ke mapping mera khayal mein
#tu donu ka size barbar krna ka lia,Nan fill kr dia
#es ka data tumhara pass nhe ta tum na NaN fill kr lia,tumhara data es ka pass nhe tha es na Nan
# fill kr lia,other then overlapping
#es mein ya issue ata ka jub hum different source sai data leta hein,tu hamara pass bohat sara columns
#Nan ka add ho jata hein
#simple concatenation mein ya issue ata hai

            sales_man_id sales_man_name	  sales_man_city	product_id	manager	Region	Sales	Amount
0	           1.0	      Asad	          Karachi	           123.0	Jawed	NaN	     NaN	NaN
1	           2.0	      Sumair	      Lahore	           123.0	Jawed	NaN	     NaN	NaN
2	           3.0	      Farjad	      Karachi	           145.0	Najam	NaN	     NaN	NaN
0	           NaN	      Asad	          NaN	               NaN	    NaN	      A	   100.0	100000.0
1	           NaN	      Hussain	      NaN	               NaN	    NaN	      B	   300.0	450000.0
2	           NaN	      Ali	          NaN	               NaN	    NaN	      C	    234.0	125000.0


172.# .reset_index()
# sara index both data ka tarteeb sai

pd.concat([df0,df2]).reset_index()

    Index   sales_man_id sales_man_name	  sales_man_city	product_id	manager	Region	Sales	Amount
1	 0          1.0	      Asad	          Karachi	           123.0	Jawed	NaN	     NaN	NaN
2	 1          2.0	      Sumair	      Lahore	           123.0	Jawed	NaN	     NaN	NaN
3	 2          3.0	      Farjad	      Karachi	           145.0	Najam	NaN	     NaN	NaN
4	 0          NaN	      Asad	          NaN	               NaN	    NaN	      A	   100.0	100000.0
5	 1          NaN	      Hussain	      NaN	               NaN	    NaN	      B	   300.0	450000.0
6	 2          NaN	      Ali	          NaN	               NaN	    NaN	      C	    234.0	125000.0


173.#              .merge
pd.merge(df0,df2)
#ub chuka ak column hee sirf merge ho raha tu ,on batana nhe parta ,wo khud he murge kr leta hai

#wo df0 mein gaya,phala salesman hai Asad
#ya jaya ga,dekha ga ka df2 mein Asad ka map ho raha ha kahee,,,us na dekha ho raha ,ya data agaya
#df0 ka Asad ko check kia us na df2 mein...or df2 ka pora record df1 ka asad mein dal dia
#means df0 ke id 1 ka aga df2 asad ka record lag gaya

#df0 ke id 2 pr sumair tha..sumair df2 mein nhe mela,sumair shamil nhe howa

#map kr raha hai ,jo columns ke value map ho rahe hai,wo record wahan sai utha kar es ka aga laga raha 
#hai

	sales_man_id	sales_man_name	     sales_man_city	   product_id	manager	Region	Sales	Amount
0	1	               Asad	                   Karachi	     123	        Jawed	A	100	   100000
1	4	              Hassan	               Lahore	     567	        Najam	G	129	   125000
2	6	              Kashif	               Hyderabad	 234	        Faisal	F	123	   825000
3	7	               Sana	                   Lahore	     567	       Faisal	D	231	   652000

# * Map          : a sai b ,matched elements ka data map ,other data which doesnt match shows Nan
# * Concatenate  : Both list add horizntally(row wise) or vertically (columns wise) both data frames add,if Columns and rows
#                  are equal
#                  if not equal then merge match figures values of both data frame,others NaN
# * Merge        : a sai b ,matched elemets ka data map,other unmatched elements not shown in the list




174.      #strip
#The strip() method removes any leading, and trailing whitespaces. Leading means at the beginning of the string, 
#trailing means at the end. You can specify which character(s) to remove, if not, any whitespaces will be removed

#df2 mein Fatima mein space hai,es lia nhe utha raha
#check krna ka lia

df2['sales_man_name']=='Fatima'

#ub fatima ke space khatam krna ka lia
#Lambda use kara ga with strip
df2['sales_man_name']=df2.sales_man_name.apply(lambda x: x.strip())
df2


175.#                       merge how:inner merge  (default:How/inner) Left to Right /By Default
pd.merge(df0,df2)   
#ub Fatima bhe a gaya

# *left or right ko jub hum na merge kia,tu wo left ka sara record dhundta raha right mein,or right
#ka sara record ly aya

# **ya inner merge khalata hai,it means interection ,means jo jo record match hota hein wo select ho jata 
#hein or jo match nhe hota,wo drop ho jata hein
# default mein merge how mein inner hai

#donu match hu ga,intersept hu ga tu he ayan ga



176. #   pd.merge(df2,df0)  (Right to Left)
#record same raha ga ,sirf sorting change ho jaya ge

   sales_man_name	Region	Sales	Amount	sales_man_id	sales_man_city	product_id	manager
0	Asad	        A	       100	100000	1	                      Karachi	123	Jawed
1	Sana	        D	       231	652000	7	                      Lahore	567	Faisal
2	Fatima	        E	       324	145000	8	                      Karachi	345	Najam
3	Kashif	        F	       123	825000	6	                      Hyderabad	234	Faisal
4	Hassan	        G	      129	125000	4	                      Lahore	567	Najam




177. #  merge how :outer merge 

pd.merge(df2,df0,how='outer')
#inner joint ,jo match krta hai wo ly kr ata hai
#or outer joint:donu ka sara record laya ga
#masla ya ho ga ,ka jub ak ka sara record laya ga ,jo match hun ga,un ko joint
#or ak ka record agar dosra sai match nhe hu ga tu jo extra columns hu ga,un ko Nan kara ga.


          sales_man_name	Region	Sales	Amount	    sales_man_id	sales_man_city	product_id	manager
0	           Asad	         A	    100.0	100000.0	      1.0          	Karachi	       123.0	Jawed
1	           Hussain	     B	    300.0	450000.0	      NaN	        NaN	            NaN	     NaN
2	           Ali	         C	    234.0	125000.0	      NaN	        NaN	            NaN	     NaN
3	           Sana	         D	   231.0	652000.0	      7.0	        Lahore	        567.0	Faisa